import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import AuthProviderClient from "@/providers/AuthProviderClient";
import ErrorBoundary from "@/components/ui/ErrorBoundary";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "FizGab",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>
          <AuthProviderClient>{children}</AuthProviderClient>
        </ErrorBoundary>
      </body>
    </html>
  );
}
